#!/usr/bin/env python3
"""{{AGENT_NAME}} Bridge — Telegram <> Claude Code Agent Bridge.

Auto-generated by openCrab (https://github.com/canaancc/openCrab).
Features: streaming output, proxy support, session persistence, cron scheduling.
"""

import asyncio
import json
import logging
import os
import re
import subprocess
import uuid
from collections import defaultdict
from pathlib import Path

from dotenv import load_dotenv
from telegram import Update
from telegram.constants import ChatAction
from telegram.error import NetworkError
from telegram.ext import Application, CommandHandler, MessageHandler, filters

from claude_agent_sdk import (
    AssistantMessage, ClaudeAgentOptions, ResultMessage,
    SystemMessage, TextBlock, ToolUseBlock, query,
)

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

BOT_DIR = Path(__file__).parent
load_dotenv(BOT_DIR / ".env")

TOKEN = os.environ["TELEGRAM_BOT_TOKEN"]
ALLOWED_USERS = {int(uid) for uid in os.environ["ALLOWED_USERS"].split(",")}
WORKSPACE = Path("{{WORKSPACE_PATH}}").expanduser()
SESSIONS_FILE = BOT_DIR / "sessions.json"
JOBS_FILE = BOT_DIR / "jobs.json"
PROXY_URL = os.environ.get("HTTPS_PROXY") or os.environ.get("HTTP_PROXY")

os.environ.pop("CLAUDECODE", None)

APPEND_PROMPT = """\
You are responding via Telegram. Keep these rules:
- Be concise — Telegram messages should be short and scannable.
- Use plain text or minimal Markdown (bold, code blocks). No headers.
- If a response would exceed ~3000 chars, summarize and offer to elaborate.
- The user cannot approve/deny tool calls — run autonomously.
- For financial operations (swap, transfer, bridge): show a preview first, \
then ask the user to reply with confirmation to proceed.
- Never initiate recurring or interval-based scheduling on your own. \
If the user wants scheduled tasks, tell them to use the /every command.
- Long-running tasks (>30s) MUST be executed in tmux:
  tmux new-session -d -s <task_name> '<command>'
  After launching, tell the user the task is running and they can use /check.
"""

logging.basicConfig(format="%(asctime)s [%(levelname)s] %(message)s", level=logging.INFO)
log = logging.getLogger("{{AGENT_ID}}-bridge")

# ---------------------------------------------------------------------------
# Session persistence
# ---------------------------------------------------------------------------

_sessions: dict[int, str] = {}


def _load_sessions() -> None:
    global _sessions
    if SESSIONS_FILE.exists():
        try:
            _sessions = {int(k): v for k, v in json.loads(SESSIONS_FILE.read_text()).items()}
        except (json.JSONDecodeError, ValueError):
            _sessions = {}


def _save_sessions() -> None:
    SESSIONS_FILE.write_text(json.dumps({str(k): v for k, v in _sessions.items()}, indent=2))


def _get_session(uid: int) -> str | None:
    return _sessions.get(uid)


def _set_session(uid: int, sid: str) -> None:
    _sessions[uid] = sid
    _save_sessions()


def _clear_session(uid: int) -> None:
    _sessions.pop(uid, None)
    _save_sessions()


# ---------------------------------------------------------------------------
# Claude SDK streaming query
# ---------------------------------------------------------------------------


async def stream_query(prompt: str, session_id: str | None = None):
    """Yield (event_type, data) tuples as Claude processes the query."""
    opts = ClaudeAgentOptions(
        system_prompt={"type": "preset", "preset": "claude_code", "append": APPEND_PROMPT},
        cwd=str(WORKSPACE),
        permission_mode="bypassPermissions",
        setting_sources=["project", "user"],
        max_turns=50,
    )
    if session_id:
        opts.resume = session_id

    async for msg in query(prompt=prompt, options=opts):
        if isinstance(msg, SystemMessage) and msg.subtype == "init":
            yield ("session_id", msg.data.get("session_id"))
        elif isinstance(msg, AssistantMessage):
            for block in msg.content:
                if isinstance(block, TextBlock):
                    yield ("text", block.text)
                elif isinstance(block, ToolUseBlock):
                    yield ("tool", block.name, block.input)
        elif isinstance(msg, ResultMessage):
            if hasattr(msg, "session_id") and msg.session_id:
                yield ("session_id", msg.session_id)
    yield ("done", None)


async def run_query(prompt: str, session_id: str | None = None) -> tuple[str, str | None]:
    """Non-streaming version for cron_runner compatibility."""
    texts, new_sid = [], None
    async for event in stream_query(prompt, session_id):
        if event[0] == "session_id":
            new_sid = event[1]
        elif event[0] == "text":
            texts.append(event[1])
    return "\n".join(texts) or "(no response)", new_sid


# ---------------------------------------------------------------------------
# Telegram helpers
# ---------------------------------------------------------------------------

MAX_MSG_LEN = 4096
STREAM_EDIT_INTERVAL = 1.5


def split_message(text: str) -> list[str]:
    if len(text) <= MAX_MSG_LEN:
        return [text]
    chunks = []
    while text:
        if len(text) <= MAX_MSG_LEN:
            chunks.append(text)
            break
        cut = text.rfind("\n", 0, MAX_MSG_LEN)
        if cut <= 0:
            cut = MAX_MSG_LEN
        chunks.append(text[:cut])
        text = text[cut:].lstrip("\n")
    return chunks


async def _edit_msg(bot, chat_id: int, message_id: int, text: str) -> None:
    """Edit a message, retry on network errors."""
    for _attempt in range(3):
        try:
            await bot.edit_message_text(
                chat_id=chat_id, message_id=message_id, text=text,
            )
            return
        except NetworkError:
            if _attempt < 2:
                await asyncio.sleep(1)
        except Exception:
            break
    try:
        await bot.edit_message_text(
            chat_id=chat_id, message_id=message_id, text=text,
        )
    except Exception:
        pass


_user_locks: dict[int, asyncio.Lock] = defaultdict(asyncio.Lock)

# ---------------------------------------------------------------------------
# Handlers
# ---------------------------------------------------------------------------


async def cmd_start(update: Update, _) -> None:
    if update.effective_user.id not in ALLOWED_USERS:
        return
    await update.message.reply_text(
        "{{AGENT_NAME}} {{AGENT_EMOJI}} online.\n"
        "/new — fresh session\n"
        "/status — session info\n"
        "/check — background tasks\n"
        "/every <schedule> <prompt> — scheduled task\n"
        "/jobs — list scheduled tasks\n"
        "/cancel <id> — cancel a task"
    )


async def cmd_new(update: Update, _) -> None:
    uid = update.effective_user.id
    if uid not in ALLOWED_USERS:
        return
    _clear_session(uid)
    await update.message.reply_text("Session cleared.")


async def cmd_status(update: Update, _) -> None:
    uid = update.effective_user.id
    if uid not in ALLOWED_USERS:
        return
    sid = _get_session(uid)
    await update.message.reply_text(
        f"Session: {sid[:16]}...\nWorkspace: {WORKSPACE}" if sid
        else f"No active session.\nWorkspace: {WORKSPACE}"
    )


async def cmd_check(update: Update, context) -> None:
    """Show running tmux sessions and their recent output."""
    uid = update.effective_user.id
    if uid not in ALLOWED_USERS:
        return

    result = subprocess.run(
        ["tmux", "list-sessions", "-F", "#{session_name}: #{session_activity}"],
        capture_output=True, text=True,
    )
    if result.returncode != 0 or not result.stdout.strip():
        await update.message.reply_text("No background tasks running.")
        return

    sessions = result.stdout.strip().splitlines()
    args = update.message.text.split()

    if len(args) >= 2:
        target = args[1]
        cap = subprocess.run(
            ["tmux", "capture-pane", "-t", target, "-p", "-l", "50"],
            capture_output=True, text=True,
        )
        if cap.returncode != 0:
            await update.message.reply_text(f"Session not found: {target}")
            return
        output = cap.stdout.strip()[-3000:] or "(empty)"
        await update.message.reply_text(f"`{target}` output:\n\n```\n{output}\n```")
    else:
        await update.message.reply_text(
            "Background tasks:\n" + "\n".join(f"- {s}" for s in sessions)
            + "\n\nUse `/check <name>` for details"
        )


async def _process_message(
    bot, chat_id: int, uid: int, prompt: str,
    session_id: str | None, save_session: bool = True,
    reply_func=None,
) -> None:
    """Core message processing — streams Claude response with live edits."""
    try:
        try:
            await bot.send_chat_action(chat_id, ChatAction.TYPING)
        except Exception:
            pass

        live_msg = None
        for _attempt in range(3):
            try:
                if reply_func:
                    live_msg = await reply_func("{{AGENT_EMOJI}} thinking...")
                else:
                    live_msg = await bot.send_message(chat_id, "{{AGENT_EMOJI}} thinking...")
                break
            except Exception:
                if _attempt < 2:
                    await asyncio.sleep(2)
        if not live_msg:
            await bot.send_message(chat_id, "Network error, please retry.")
            return
        live_msg_id = live_msg.message_id

        got_first_text = asyncio.Event()

        async def _keep_typing():
            while not got_first_text.is_set():
                try:
                    await bot.send_chat_action(chat_id, ChatAction.TYPING)
                except Exception:
                    pass
                try:
                    await asyncio.wait_for(got_first_text.wait(), timeout=5.0)
                    return
                except asyncio.TimeoutError:
                    pass

        typing_task = asyncio.create_task(_keep_typing())

        accumulated = ""
        last_edit_time = 0.0
        overflow_texts = []

        async for event in stream_query(prompt, session_id):
            event_type = event[0]

            if event_type == "session_id":
                if event[1] and save_session:
                    _set_session(uid, event[1])

            elif event_type == "tool":
                tool_name, tool_input = event[1], event[2]

                if tool_name == "Bash":
                    cmd = tool_input.get("command", "")
                    cmd_display = cmd[:80] + "..." if len(cmd) > 80 else cmd
                    status = f"{{{{AGENT_EMOJI}}}} running...\n`{cmd_display}`"
                elif tool_name in ("Read", "Glob", "Grep"):
                    target = tool_input.get("file_path") or tool_input.get("pattern") or ""
                    status = f"{{{{AGENT_EMOJI}}}} reading... `{target}`"
                elif tool_name in ("Edit", "Write"):
                    target = tool_input.get("file_path", "")
                    status = f"{{{{AGENT_EMOJI}}}} writing... `{target}`"
                else:
                    status = f"{{{{AGENT_EMOJI}}}} {tool_name}..."

                await _edit_msg(bot, chat_id, live_msg_id, status)
                last_edit_time = asyncio.get_event_loop().time()

            elif event_type == "text":
                if not got_first_text.is_set():
                    got_first_text.set()

                candidate = (accumulated + "\n" + event[1]).strip() if accumulated else event[1]

                if len(candidate) > MAX_MSG_LEN:
                    overflow_texts.append(event[1])
                else:
                    accumulated = candidate

                    now = asyncio.get_event_loop().time()
                    if now - last_edit_time >= STREAM_EDIT_INTERVAL:
                        await _edit_msg(bot, chat_id, live_msg_id, accumulated)
                        last_edit_time = now

            elif event_type == "done":
                break

        got_first_text.set()
        typing_task.cancel()

        if accumulated:
            await _edit_msg(bot, chat_id, live_msg_id, accumulated)
        else:
            await _edit_msg(bot, chat_id, live_msg_id, "(no response)")

        if overflow_texts:
            overflow_combined = "\n".join(overflow_texts)
            for chunk in split_message(overflow_combined):
                try:
                    await bot.send_message(chat_id, chunk)
                except Exception:
                    pass

    except Exception as e:
        log.exception("Error processing message")
        await bot.send_message(chat_id, f"Error: {e}")


async def handle_message(update: Update, context) -> None:
    uid = update.effective_user.id
    if uid not in ALLOWED_USERS or not update.message.text:
        return
    chat_id = update.effective_chat.id
    bot = context.application.bot

    if _user_locks[uid].locked():
        await update.message.reply_text("Previous message still processing, please wait...")
        return

    async with _user_locks[uid]:
        sid = _get_session(uid)
        log.info("Query from %s (session=%s): %s", uid, sid and sid[:8], update.message.text[:80])
        await _process_message(
            bot, chat_id, uid, update.message.text,
            session_id=sid, save_session=True,
            reply_func=update.message.reply_text,
        )


# ---------------------------------------------------------------------------
# Scheduled jobs — /every, /jobs, /cancel (crontab-based)
# ---------------------------------------------------------------------------

CRON_RUNNER = BOT_DIR / "cron_runner.py"
PYTHON = str(BOT_DIR / ".venv/bin/python3")
CRON_COMMENT_PREFIX = "{{AGENT_ID}}-job:"

_job_defs: dict[str, dict] = {}


def _load_jobs() -> None:
    global _job_defs
    if JOBS_FILE.exists():
        try:
            _job_defs = json.loads(JOBS_FILE.read_text())
        except (json.JSONDecodeError, ValueError):
            _job_defs = {}


def _save_jobs() -> None:
    JOBS_FILE.write_text(json.dumps(_job_defs, indent=2, ensure_ascii=False))


def _parse_schedule(spec: str) -> str:
    """Parse schedule spec into cron expression.

    "30m" -> "*/30 * * * *", "1h" -> "0 * * * *", "6h" -> "0 */6 * * *",
    "1d" -> "0 0 * * *", "8:00" -> "0 8 * * *", "14:30" -> "30 14 * * *"
    """
    spec = spec.strip()
    m = re.fullmatch(r"(\d+)([mhd])", spec)
    if m:
        n, unit = int(m.group(1)), m.group(2)
        if unit == "m":
            return f"*/{n} * * * *"
        elif unit == "h":
            return "0 * * * *" if n == 1 else f"0 */{n} * * *"
        elif unit == "d":
            return "0 0 * * *"
    m = re.fullmatch(r"(\d{1,2}):(\d{2})", spec)
    if m:
        return f"{int(m.group(2))} {int(m.group(1))} * * *"
    raise ValueError(f"Unknown schedule format: {spec}. Use 30m/6h/1d or HH:MM")


def _read_crontab() -> str:
    result = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
    return result.stdout if result.returncode == 0 else ""


def _write_crontab(content: str) -> None:
    subprocess.run(["crontab", "-"], input=content, text=True, check=True)


def _add_cron_entry(job_id: str, cron_expr: str) -> None:
    existing = _read_crontab()
    comment = f"# {CRON_COMMENT_PREFIX}{job_id}"
    cron_line = f"{cron_expr} cd {BOT_DIR} && {PYTHON} {CRON_RUNNER} --job-id {job_id} >> {BOT_DIR}/cron.log 2>&1"
    new_entry = f"{comment}\n{cron_line}\n"
    if existing and not existing.endswith("\n"):
        existing += "\n"
    _write_crontab(existing + new_entry)


def _remove_cron_entry(job_id: str) -> None:
    existing = _read_crontab()
    if not existing:
        return
    lines = existing.splitlines()
    filtered, skip_next = [], False
    for line in lines:
        if line.strip() == f"# {CRON_COMMENT_PREFIX}{job_id}":
            skip_next = True
            continue
        if skip_next:
            skip_next = False
            continue
        filtered.append(line)
    _write_crontab("\n".join(filtered) + "\n" if filtered else "")


async def cmd_every(update: Update, context) -> None:
    """Usage: /every <schedule> <prompt>"""
    uid = update.effective_user.id
    if uid not in ALLOWED_USERS:
        return
    args = update.message.text.split(None, 2)
    if len(args) < 3:
        await update.message.reply_text(
            "Usage: /every <schedule> <prompt>\n"
            "Schedule: 30m, 6h, 1d, or HH:MM\n"
            "Example: /every 8:00 morning briefing"
        )
        return
    schedule_spec, prompt = args[1], args[2]
    try:
        cron_expr = _parse_schedule(schedule_spec)
    except ValueError as e:
        await update.message.reply_text(str(e))
        return

    job_id = uuid.uuid4().hex[:12]
    job_def = {
        "prompt": prompt,
        "chat_id": update.effective_chat.id,
        "user_id": uid,
        "schedule": schedule_spec,
        "cron_expr": cron_expr,
    }
    _job_defs[job_id] = job_def
    _save_jobs()
    try:
        _add_cron_entry(job_id, cron_expr)
    except subprocess.CalledProcessError as e:
        del _job_defs[job_id]
        _save_jobs()
        await update.message.reply_text(f"Failed to write crontab: {e}")
        return
    await update.message.reply_text(
        f"Job {job_id[:8]} created.\nSchedule: {schedule_spec} ({cron_expr})\nPrompt: {prompt}"
    )


async def cmd_jobs(update: Update, _) -> None:
    uid = update.effective_user.id
    if uid not in ALLOWED_USERS:
        return
    if not _job_defs:
        await update.message.reply_text("No scheduled jobs.")
        return
    lines = [f"- {jid[:8]} | {jd['schedule']} ({jd.get('cron_expr','?')}) | {jd['prompt'][:50]}"
             for jid, jd in _job_defs.items()]
    await update.message.reply_text("Scheduled jobs:\n" + "\n".join(lines))


async def cmd_cancel(update: Update, context) -> None:
    uid = update.effective_user.id
    if uid not in ALLOWED_USERS:
        return
    args = update.message.text.split()
    if len(args) < 2:
        await update.message.reply_text("Usage: /cancel <job_id>")
        return
    target = args[1]
    matched = [jid for jid in _job_defs if jid.startswith(target)]
    if not matched:
        await update.message.reply_text(f"No job matching '{target}'.")
        return
    for jid in matched:
        _remove_cron_entry(jid)
        del _job_defs[jid]
        log.info("Cancelled job %s", jid[:8])
    _save_jobs()
    await update.message.reply_text(f"Cancelled {len(matched)} job(s).")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    _load_sessions()
    _load_jobs()

    from telegram.request import HTTPXRequest
    req_kwargs = {"read_timeout": 60, "write_timeout": 60, "connect_timeout": 30}
    if PROXY_URL:
        req_kwargs["proxy"] = PROXY_URL
    builder = Application.builder().token(TOKEN)
    builder = builder.request(HTTPXRequest(**req_kwargs)).get_updates_request(HTTPXRequest(**req_kwargs))
    app = builder.build()

    app.add_handler(CommandHandler("start", cmd_start))
    app.add_handler(CommandHandler("new", cmd_new))
    app.add_handler(CommandHandler("status", cmd_status))
    app.add_handler(CommandHandler("check", cmd_check))
    app.add_handler(CommandHandler("every", cmd_every))
    app.add_handler(CommandHandler("jobs", cmd_jobs))
    app.add_handler(CommandHandler("cancel", cmd_cancel))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))
    log.info("{{AGENT_NAME}} Bridge started. Workspace: %s", WORKSPACE)
    log.info("Loaded %d job definition(s)", len(_job_defs))
    app.run_polling(drop_pending_updates=True)


if __name__ == "__main__":
    main()
