#!/usr/bin/env python3
"""Standalone cron job runner — called by system crontab.

Auto-generated by assistant-create skill.
Usage: python3 cron_runner.py --job-id <id>
"""

import argparse
import asyncio
import json
import logging
import os
import sys
from pathlib import Path

import httpx
from dotenv import load_dotenv

from claude_agent_sdk import (
    AssistantMessage, ClaudeAgentOptions, ResultMessage,
    SystemMessage, TextBlock, query,
)

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

BOT_DIR = Path(__file__).parent
load_dotenv(BOT_DIR / ".env")

os.environ.pop("CLAUDECODE", None)

TOKEN = os.environ["TELEGRAM_BOT_TOKEN"]
JOBS_FILE = BOT_DIR / "jobs.json"
SESSIONS_FILE = BOT_DIR / "sessions.json"
WORKSPACE = Path("{{WORKSPACE_PATH}}").expanduser()

APPEND_PROMPT = """\
You are responding via Telegram. Keep these rules:
- Be concise — Telegram messages should be short and scannable.
- Use plain text or minimal Markdown (bold, code blocks). No headers.
- If a response would exceed ~3000 chars, summarize and offer to elaborate.
- The user cannot approve/deny tool calls — run autonomously.
- Never initiate recurring or interval-based scheduling on your own. If the user wants scheduled tasks, tell them to use the /every command in this chat.
"""

logging.basicConfig(format="%(asctime)s [%(levelname)s] %(message)s", level=logging.INFO)
log = logging.getLogger("{{AGENT_ID}}-cron")

MAX_MSG_LEN = 4096


# ---------------------------------------------------------------------------
# Session helpers
# ---------------------------------------------------------------------------


def _load_sessions() -> dict[int, str]:
    if SESSIONS_FILE.exists():
        try:
            return {int(k): v for k, v in json.loads(SESSIONS_FILE.read_text()).items()}
        except (json.JSONDecodeError, ValueError):
            pass
    return {}


def _save_sessions(sessions: dict[int, str]) -> None:
    SESSIONS_FILE.write_text(json.dumps({str(k): v for k, v in sessions.items()}, indent=2))


# ---------------------------------------------------------------------------
# Job helpers
# ---------------------------------------------------------------------------


def _load_job(job_id: str) -> dict:
    if not JOBS_FILE.exists():
        log.error("jobs.json not found")
        sys.exit(1)
    jobs = json.loads(JOBS_FILE.read_text())
    if job_id not in jobs:
        log.error("Job %s not found in jobs.json", job_id)
        sys.exit(1)
    return jobs[job_id]


# ---------------------------------------------------------------------------
# Claude SDK query
# ---------------------------------------------------------------------------


async def run_query(prompt: str, session_id: str | None = None) -> tuple[str, str | None]:
    opts = ClaudeAgentOptions(
        system_prompt={"type": "preset", "preset": "claude_code", "append": APPEND_PROMPT},
        cwd=str(WORKSPACE),
        permission_mode="bypassPermissions",
        setting_sources=["project", "user"],
        max_turns=50,
    )
    if session_id:
        opts.resume = session_id

    texts, new_sid = [], None
    async for msg in query(prompt=prompt, options=opts):
        if isinstance(msg, SystemMessage) and msg.subtype == "init":
            new_sid = msg.data.get("session_id")
        elif isinstance(msg, AssistantMessage):
            for block in msg.content:
                if isinstance(block, TextBlock):
                    texts.append(block.text)
        elif isinstance(msg, ResultMessage):
            if hasattr(msg, "session_id") and msg.session_id:
                new_sid = msg.session_id
    return "\n".join(texts) or "(no response)", new_sid


# ---------------------------------------------------------------------------
# Telegram send
# ---------------------------------------------------------------------------


def _split_message(text: str) -> list[str]:
    if len(text) <= MAX_MSG_LEN:
        return [text]
    chunks = []
    while text:
        if len(text) <= MAX_MSG_LEN:
            chunks.append(text)
            break
        cut = text.rfind("\n", 0, MAX_MSG_LEN)
        if cut <= 0:
            cut = MAX_MSG_LEN
        chunks.append(text[:cut])
        text = text[cut:].lstrip("\n")
    return chunks


async def send_telegram(chat_id: int, text: str) -> None:
    url = f"https://api.telegram.org/bot{TOKEN}/sendMessage"
    async with httpx.AsyncClient(timeout=30) as client:
        for chunk in _split_message(text):
            resp = await client.post(url, json={
                "chat_id": chat_id,
                "text": chunk,
                "parse_mode": "Markdown",
            })
            if resp.status_code != 200 or not resp.json().get("ok"):
                await client.post(url, json={"chat_id": chat_id, "text": chunk})


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


async def main(job_id: str) -> None:
    job = _load_job(job_id)
    prompt = job["prompt"]
    chat_id = job["chat_id"]
    user_id = job["user_id"]

    log.info("Running job %s: %s", job_id[:8], prompt[:60])

    sessions = _load_sessions()
    session_id = sessions.get(user_id)

    try:
        response, new_sid = await run_query(prompt, session_id)
        if new_sid:
            sessions[user_id] = new_sid
            _save_sessions(sessions)

        header = f"[scheduled: {prompt[:40]}]\n\n"
        await send_telegram(chat_id, header + response)
        log.info("Job %s completed successfully", job_id[:8])

    except Exception as e:
        log.exception("Job %s failed", job_id[:8])
        await send_telegram(chat_id, f"[job {job_id[:8]} error] {e}")
        sys.exit(1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Cron job runner")
    parser.add_argument("--job-id", required=True, help="Job ID from jobs.json")
    args = parser.parse_args()
    asyncio.run(main(args.job_id))
